In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as f
from torch import Tensor

x = Tensor([9.0])
y = Tensor([3.0])
z = Tensor([x,y])

x/z.sum()

tensor([0.7500])

## 2 Phase

In [2]:
import numpy as np
import pandas as pd

cycle       = 60
min_green   = 15
interval    = 5

x = np.arange(min_green, cycle-min_green+interval, interval)
y = [cycle-i for i in x]

arry = np.array([x,y])
arry = np.transpose(arry)
arry

array([[15, 45],
       [20, 40],
       [25, 35],
       [30, 30],
       [35, 25],
       [40, 20],
       [45, 15]])

In [3]:
import traci
from sumolib import checkBinary
import sys
import os

if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("please declare environment variable 'SUMO_HOME'")

sumocfg_path="Simulation_Environment\Static DQN Simulation\osm.sumocfg"
traci.start([checkBinary('sumo'),'-c', sumocfg_path])
tl = traci.trafficlight.getIDList()[0]

In [4]:
tl

'4889475255'

In [11]:
import re
logic = traci.trafficlight.getCompleteRedYellowGreenDefinition(tl)[0]
pattern = r'(y|Y)'
phases_with_yellow = [i.state for i in logic.getPhases()]
phases = [idx for idx, i in enumerate(phases_with_yellow) if re.search(pattern, i) != None]
phases

[1, 3]

In [6]:
phases_with_yellow

['GGGrrsrrrrGGGrrsrrrr',
 'yyyrrsrrrryyyrrsrrrr',
 'srrrrGGGrrsrrrrGGGrr',
 'srrrryyyrrsrrrryyyrr']

In [15]:
import numpy as np

x=[]
for i in range(3):
    x.append([1,2,3])
x = np.array(x)
all = np.array([])

for i in range(x.shape[1]):
    val = x[:,i].mean()
    all = np.append(all,val)

all

array([1., 2., 3.])